tourapi:
  service-key: "bSScng/3usRy3I/o/X8+nudWEsf51V58EU9h5wQ6AU90UYD0f4bsCbZqYlTEp0FX7oDEbuppdUGV7S+mSror6A=="
  base-url: "https://apis.data.go.kr/B551011/KorPetTourService"
  app-name: "PetTripApp"
  os: "ETC"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pet_trip_service
    username: postgres
    password: 200905
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
