spring:
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true} # 기본값 true
      path: ${H2_CONSOLE_PATH:/h2-console}
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
